digits:
  length_50: 50
  length_255: 255
  length_6: 6

regex:
  email: !ruby/regexp '/\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/'

gravatar:
  url: "https://secure.gravatar.com/avatar/"
  default_size: 80
  size_view: 200
  users_size: 50

user:
  per_page: 5

role:
  user: 0
  admin: 1

image:
  max_size: 5
  accept_format: ["image/jpeg", "image/gif", "image/png"]
  accept_format_html: "image/jpeg,image/gif,image/png"
  size_500_500: [50, 50]
